#!/bin/sh
set -e

BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/libplacebo_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/libplacebo_options) "$@"
    unset -v IFS
fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

echo Using libplacebo options: "$@"

cd "$BUILD"/libplacebo
meson build --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" -Ddefault_library=static "$@"
