#!/bin/sh
set -e

BUILD="$(pwd)"
newline="
"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/libplacebo
meson --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" -Ddefault_library=static build
